version: '3.4'

services:
    db:
        image: postgres
        container_name: h3micro_db
        restart: on-failure
        volumes:
            - ./db:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: mohamad
            POSTGRES_PASSWORD: 123321
        ports:
            - '5432:5432'
        networks:
            - h3micronetwork

    client:
        build: ./client
        container_name: h3micro_client
        # stdin_open: true
        ports:
            - '5173:5173'
            - '5174:5174'
        volumes:
            - ./client:/usr/src/client
            - /usr/src/client/node_modules
        links:
            - server
        restart: on-failure
        networks:
            - h3micronetwork

    server:
        build: ./server
        container_name: h3micro_server
        ports:
            - '8000:8000'
        volumes:
            - ./server:/usr/src/server
            - /usr/src/server/node_modules
        links:
            - db
        environment:
            PORT: 8000
            POSTGRES_URI: postgres://mohamad:123321@db:5432/postgres
            # POSTGRES_URI: postgres://h3microdb_user:yjU2aGNkKecLUhA4LLh3HAqzunXaLh1P@dpg-ckn625p1rp3c7396dom0-a.frankfurt-postgres.render.com/h3microdb?ssl=true
        restart: on-failure
        networks:
            - h3micronetwork
        depends_on:
            - db
            - elasticsearch

    reverse_proxy_server:
        image: nginx
        container_name: h3micro_nginx_server
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./reverse_proxy/server/nginx.conf:/etc/nginx/nginx.conf
            - ./reverse_proxy/server/ssl:/etc/nginx/ssl
        depends_on:
            - server
        networks:
            - h3micronetwork
        restart: on-failure:3

    reverse_proxy_client:
        image: nginx
        container_name: h3micro_nginx_client
        ports:
            - '800:800'
            - '444:444'
        volumes:
            - ./reverse_proxy/client/nginx.conf:/etc/nginx/nginx.conf
            - ./reverse_proxy/client/ssl:/etc/nginx/ssl
        depends_on:
            - client
        networks:
            - h3micronetwork
        restart: on-failure:3

    cadvisor:
        image: gcr.io/cadvisor/cadvisor-arm64:v0.47.2
        container_name: h3micro_cadvisor
        privileged: true
        ports:
            - '8080:8080'
        devices:
            - /dev/kmsg:/dev/kmsg
        volumes:
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /etc/machine-id:/etc/machine-id:ro
            - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
        networks:
            - h3micronetwork
        restart: always
        deploy:
            mode: global
        depends_on:
            - elasticsearch

    grafana:
        image: grafana/grafana:latest
        container_name: h3micro_grafana
        ports:
            - '3000:3000'
        volumes:
            - ./grafana/data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        networks:
            - h3micronetwork
        depends_on:
            - cadvisor
        restart: on-failure

    prometheus:
        image: prom/prometheus
        container_name: h3micro_prometheus
        ports:
            - '9090:9090'
        volumes:
            - ./prometheus/config:/etc/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        networks:
            - h3micronetwork
        restart: on-failure

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
        container_name: h3micro_elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
        ports:
            - '9200:9200'
        networks:
            - h3micronetwork
        restart: on-failure

networks:
    h3micronetwork:
        driver: bridge
