version: '3.4'

services:
    db:
        image: postgres
        container_name: h3micro_db
        restart: on-failure
        volumes:
            - ./db:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: mohamad
            POSTGRES_PASSWORD: 123321
        ports:
            - '5432:5432'
        networks:
            - h3micronetwork

    client:
        build: ./client
        container_name: h3micro_client
        # stdin_open: true
        ports:
            - '5173:5173'
            - '5174:5174'
        volumes:
            - ./client:/usr/src/client
            - /usr/src/client/node_modules
        links:
            - server
        restart: on-failure
        networks:
            - h3micronetwork

    server:
        build: ./server
        container_name: h3micro_server
        ports:
            - '8000:8000'
        volumes:
            - ./server:/usr/src/server
            - /usr/src/server/node_modules
        links:
            - db
        environment:
            PORT: 8000
            POSTGRES_URI: postgres://h3microdb_user:yjU2aGNkKecLUhA4LLh3HAqzunXaLh1P@dpg-ckn625p1rp3c7396dom0-a.frankfurt-postgres.render.com/h3microdb?ssl=true
        restart: on-failure
        networks:
            - h3micronetwork

    reverse_proxy_server:
        image: nginx
        container_name: h3micro_nginx_server
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./reverse_proxy/server/nginx.conf:/etc/nginx/nginx.conf
            - ./reverse_proxy/server/ssl:/etc/nginx/ssl
        depends_on:
            - server
        networks:
            - h3micronetwork
        restart: on-failure:3

    reverse_proxy_client:
        image: nginx
        container_name: h3micro_nginx_client
        ports:
            - '800:800'
            - '444:444'
        volumes:
            - ./reverse_proxy/client/nginx.conf:/etc/nginx/nginx.conf
            - ./reverse_proxy/client/ssl:/etc/nginx/ssl
        depends_on:
            - client
        networks:
            - h3micronetwork
        restart: on-failure:3

networks:
    h3micronetwork:
        driver: bridge
