# Use postgres/example user/password credentials
version: '3.1'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: mohamad
            POSTGRES_PASSWORD: 123321
