global:
    scrape_interval: 5s

scrape_configs:
    - job_name: 'backend'
      static_configs:
          - targets: ['server:8000']

    - job_name: 'backend_reverse_proxy'
      scheme: https
      tls_config:
          insecure_skip_verify: true
      static_configs:
          - targets: ['reverse_proxy_server:443']
